services:
  postgres:
    image: postgres:16
    container_name: day003-postgres
    environment:
      POSTGRES_DB: day003
      POSTGRES_USER: day003
      POSTGRES_PASSWORD: day003
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
